name = "prequel"
version = "0.1.0"
description = "A markup language to define ER schemas"

# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.30"
non_empty_list = "~> 1.0"
gleam_community_ansi = "~> 1.1"

[dev-dependencies]
gleeunit = "~> 0.10"
gap = "~> 0.5"
simplifile = "~> 0.1"
