name = "prequel"
version = "0.1.0"
description = "A markup language to define ER schemas"

licences = ["MIT"]
repository = { type = "github", user = "giacomocavalieri", repo = "prequel" }
# links = [{ title = "Website", href = "https://gleam.run" }]

internal_modules = [
  "prequel/internals",
  "prequel/internals/*",
]

[dependencies]
gleam_stdlib = "~> 0.30"
non_empty_list = "~> 1.1"
gleam_community_ansi = "~> 1.1"

[dev-dependencies]
gleeunit = "~> 0.10"
gap = "~> 0.5"
simplifile = "~> 0.1"
